name: Hourly NFL PQ Update

on:
  schedule:
    - cron: "23 * * * *"          # Hourly update at :23
    - cron: "*/15 13-23 * * 0,1"   # Every 15 mins (approx 8AM-7PM EST) on Sun/Mon
  workflow_dispatch:              # Keeps the "Run Workflow" button active

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas nfl_data_py pytz

      - name: Run rankings script
        run: python update_rankings.py

      - name: Commit and push changes
        run: |
          git config --global user.name "NFL Stats Bot"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Automated PQ Update" || exit 0
          git push
